"""Zero-copy .a7p ballistic profile access for MicroPython.

Mirrors the load/loads/dump/dumps API of the `a7p` PyPI package (see
py/src/a7p/a7p.py), but Profile never builds an intermediate Python
object graph for its scalar/array fields: `_a7p.decode()` (the native
module, see src/a7p_mp.c) writes nanopb's parsed profedit_Payload
directly into Profile._buf, and Profile._s is a uctypes struct overlaid
on that same bytearray, so `profile.profile.zero_x` reads/writes the
exact memory nanopb will later re-encode from.

Requires the compiled `_a7p` native module (natmod/Makefile) to be
importable. The uctypes layout constants below (PAYLOAD_SIZE,
PAYLOAD_DESC, PROFILE_STRINGS, PAYLOAD_PROFILE_OFFSET) are generated
by tools/gen_layout.py, which rewrites everything between the BEGIN/END
GENERATED markers in place -- re-run it after regenerating
profedit.pb.h, it does not touch the rest of this file.
"""

import binascii
import hashlib

import uctypes

import _a7p

# BEGIN GENERATED (tools/gen_layout.py) -- do not edit by hand
PAYLOAD_SIZE = 3988
PROFILE_SIZE = 3984
SWPOS_SIZE = 20
COEFROW_SIZE = 8

SWPOS_DESC = {
    "c_idx": uctypes.INT32 | 0,
    "reticle_idx": uctypes.INT32 | 4,
    "zoom": uctypes.INT32 | 8,
    "distance": uctypes.INT32 | 12,
    "distance_from": uctypes.UINT32 | 16,
}

COEFROW_DESC = {
    "bc_cd": uctypes.INT32 | 0,
    "mv": uctypes.INT32 | 4,
}

# byte offset/size of the fixed char[] string fields -- sliced directly out
# of the backing bytearray (also zero-copy: bytearray slicing is a copy in
# CPython but MicroPython's bytearray supports memoryview slices; callers
# that want to mutate in place should use Profile.set_str()).
PROFILE_STRINGS = {
    "profile_name": (0, 51),
    "cartridge_name": (51, 51),
    "bullet_name": (102, 51),
    "short_name_top": (153, 9),
    "short_name_bot": (162, 9),
    "user_note": (171, 1025),
    "caliber": (3880, 51),
    "device_uuid": (3931, 51),
}

# PROFILE_DESC covers every scalar/enum field plus the three repeated
# arrays (as uctypes ARRAY-of-struct / ARRAY-of-scalar) for true zero-copy
# field access. String fields are intentionally left out of this
# descriptor -- see PROFILE_STRINGS above -- since uctypes has no
# fixed-char-array-as-str type.
PROFILE_DESC = {
    "zero_x": uctypes.INT32 | 1196,
    "zero_y": uctypes.INT32 | 1200,
    "sc_height": uctypes.INT32 | 1204,
    "r_twist": uctypes.INT32 | 1208,
    "c_muzzle_velocity": uctypes.INT32 | 1212,
    "c_zero_temperature": uctypes.INT32 | 1216,
    "c_t_coeff": uctypes.INT32 | 1220,
    "c_zero_distance_idx": uctypes.INT32 | 1224,
    "c_zero_air_temperature": uctypes.INT32 | 1228,
    "c_zero_air_pressure": uctypes.INT32 | 1232,
    "c_zero_air_humidity": uctypes.INT32 | 1236,
    "c_zero_w_pitch": uctypes.INT32 | 1240,
    "c_zero_p_temperature": uctypes.INT32 | 1244,
    "b_diameter": uctypes.INT32 | 1248,
    "b_weight": uctypes.INT32 | 1252,
    "b_length": uctypes.INT32 | 1256,
    "twist_dir": uctypes.UINT32 | 1260,
    "bc_type": uctypes.UINT32 | 1264,
    "switches_count": uctypes.UINT16 | 1268,
    "switches": (1272 | uctypes.ARRAY, 10, SWPOS_DESC),
    "distances_count": uctypes.UINT16 | 1472,
    "distances": (1476 | uctypes.ARRAY, 200 | uctypes.INT32),
    "coef_rows_count": uctypes.UINT16 | 2276,
    "coef_rows": (2280 | uctypes.ARRAY, 200, COEFROW_DESC),
}

# Payload = {has_profile: bool, profile: Profile} -- the wire envelope every
# .a7p file's protobuf body decodes into.
PAYLOAD_DESC = {
    "has_profile": uctypes.UINT8 | 0,
    "profile": (4, PROFILE_DESC),
}
PAYLOAD_PROFILE_OFFSET = 4
# END GENERATED


class A7PError(Exception):
    pass


class A7PChecksumError(A7PError):
    pass


class A7PDecodeError(A7PError):
    pass


class A7PValidationError(A7PError):
    pass


# Order must match the enum in src/a7p_validate_err.h exactly -- index 0
# ("valid") is never raised, _a7p.validate()'s return value indexes directly
# into this tuple. Thresholds referenced below come from a7p_validate.h
# (generated by tools/gen_validate.py from schema/a7p.schema.json).
_VALIDATE_MESSAGES = (
    "valid",
    "profile: has_profile is false (no profile present)",
    "zero_x: out of range",
    "zero_y: out of range",
    "sc_height: out of range",
    "r_twist: out of range",
    "twist_dir: invalid enum value",
    "c_muzzle_velocity: out of range",
    "c_zero_temperature: out of range",
    "c_t_coeff: out of range",
    "c_zero_distance_idx: out of range",
    "c_zero_air_temperature: out of range",
    "c_zero_air_pressure: out of range",
    "c_zero_air_humidity: out of range",
    "c_zero_w_pitch: out of range",
    "c_zero_p_temperature: out of range",
    "b_diameter: out of range",
    "b_weight: out of range",
    "b_length: out of range",
    "bc_type: invalid enum value",
    "coef_rows: too many rows (or none) for bc_type",
    "coef_rows[].bc_cd: out of range",
    "coef_rows[].mv: out of range for bc_type",
    "coef_rows[].mv: duplicate value (must be unique except 0)",
    "switches[].c_idx: out of range",
    "switches[].zoom: out of range",
    "switches[].reticle_idx: out of range",
    "switches[].distance: out of range",
    "switches[].distance_from: invalid enum value",
    "distances[]: out of range",
)


class Profile:
    """One .a7p payload, backed by a single fixed-size bytearray."""

    def __init__(self):
        self._buf = bytearray(PAYLOAD_SIZE)
        self._s = uctypes.struct(uctypes.addressof(self._buf), PAYLOAD_DESC, uctypes.LITTLE_ENDIAN)

    @property
    def has_profile(self):
        return bool(self._s.has_profile)

    @property
    def profile(self):
        """The nested profedit_Profile uctypes struct -- e.g.
        `profile.profile.zero_x`, `profile.profile.distances[0]`,
        `profile.profile.switches[0].zoom`, `profile.profile.coef_rows_count`.
        """
        return self._s.profile

    def get_str(self, name):
        """Reads a fixed char[] field (e.g. "profile_name", "user_note")."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        raw = bytes(self._buf[base:base + size])
        end = raw.find(b"\x00")
        if end < 0:
            end = len(raw)
        return raw[:end].decode()

    def set_str(self, name, value):
        """Writes a fixed char[] field in place (null-padded, NUL-terminated)."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        encoded = value.encode()
        if len(encoded) > size - 1:
            raise ValueError("a7p: %s exceeds %d bytes" % (name, size - 1))
        self._buf[base:base + size] = bytes(size)
        self._buf[base:base + len(encoded)] = encoded

    def decode(self, data):
        """Decodes a raw protobuf-encoded Payload body into this Profile."""
        if not _a7p.decode(self._buf, data):
            raise A7PDecodeError("a7p: failed to decode Payload")
        return self

    def encode(self):
        """Encodes this Profile back into a raw protobuf Payload body."""
        return _a7p.encode(self._buf)

    def validate(self):
        """Checks value bounds/enum validity/coef_rows rules from
        schema/a7p.schema.json (numeric ranges only -- string lengths and
        array counts are already enforced structurally by the fixed buffer
        and uctypes array sizes, so aren't re-checked here). Raises
        A7PValidationError on the first rule that fails; returns None.

        Note: some real .a7p files (e.g. go/assets/example.a7p) have
        distances[0] == 0, which the canonical schema's `distances[].minimum:
        100` rejects -- a known, pre-existing data/schema discrepancy (see
        docs/DESIGN-schema-unification.md), not a bug in this check.
        """
        code = _a7p.validate(self._buf)
        if code != 0:
            raise A7PValidationError("a7p: %s" % _VALIDATE_MESSAGES[code])


def loads(data):
    """Parses a full .a7p file's bytes (32-byte hex md5 prefix + protobuf body)."""
    if len(data) < 32:
        raise A7PChecksumError("a7p: input too short for md5 prefix")
    body = data[32:]
    got = binascii.hexlify(hashlib.md5(body).digest())
    want = bytes(data[:32])
    if got != want:
        raise A7PChecksumError("a7p: md5 checksum mismatch")
    return Profile().decode(body)


def load(fp):
    """Reads a .a7p file from an already-open binary file object (like json.load)."""
    return loads(fp.read())


def dumps(profile):
    """Serializes a Profile back to full .a7p file bytes (md5 prefix + body)."""
    body = profile.encode()
    hexdigest = binascii.hexlify(hashlib.md5(body).digest())
    return hexdigest + body


def dump(profile, fp):
    """Writes a full .a7p file to an already-open binary file object (like json.dump)."""
    fp.write(dumps(profile))
