"""Zero-copy .a7p ballistic profile access for MicroPython.

Mirrors the load/loads/dump/dumps API of the `a7p` PyPI package (see
py/src/a7p/a7p.py), but Profile never builds an intermediate Python
object graph for its scalar/array fields: `_a7p.decode()` (the native
module, see src/a7p_mp.c) writes nanopb's parsed profedit_Payload
directly into Profile._buf, and Profile._s is a uctypes struct overlaid
on that same bytearray, so `profile.profile.zero_x` reads/writes the
exact memory nanopb will later re-encode from.

Requires the compiled `_a7p` native module (natmod/Makefile) and
a7p_layout.py (generated by tools/gen_layout.py) to be importable.
"""

import binascii
import hashlib

import uctypes

import _a7p
from a7p_layout import (
    PAYLOAD_DESC,
    PAYLOAD_PROFILE_OFFSET,
    PAYLOAD_SIZE,
    PROFILE_STRINGS,
)


class A7PError(Exception):
    pass


class A7PChecksumError(A7PError):
    pass


class A7PDecodeError(A7PError):
    pass


class Profile:
    """One .a7p payload, backed by a single fixed-size bytearray."""

    def __init__(self):
        self._buf = bytearray(PAYLOAD_SIZE)
        self._s = uctypes.struct(uctypes.addressof(self._buf), PAYLOAD_DESC, uctypes.LITTLE_ENDIAN)

    @property
    def has_profile(self):
        return bool(self._s.has_profile)

    @property
    def profile(self):
        """The nested profedit_Profile uctypes struct -- e.g.
        `profile.profile.zero_x`, `profile.profile.distances[0]`,
        `profile.profile.switches[0].zoom`, `profile.profile.coef_rows_count`.
        """
        return self._s.profile

    def get_str(self, name):
        """Reads a fixed char[] field (e.g. "profile_name", "user_note")."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        raw = bytes(self._buf[base:base + size])
        end = raw.find(b"\x00")
        if end < 0:
            end = len(raw)
        return raw[:end].decode()

    def set_str(self, name, value):
        """Writes a fixed char[] field in place (null-padded, NUL-terminated)."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        encoded = value.encode()
        if len(encoded) > size - 1:
            raise ValueError("a7p: %s exceeds %d bytes" % (name, size - 1))
        self._buf[base:base + size] = bytes(size)
        self._buf[base:base + len(encoded)] = encoded

    def decode(self, data):
        """Decodes a raw protobuf-encoded Payload body into this Profile."""
        if not _a7p.decode(self._buf, data):
            raise A7PDecodeError("a7p: failed to decode Payload")
        return self

    def encode(self):
        """Encodes this Profile back into a raw protobuf Payload body."""
        return _a7p.encode(self._buf)


def loads(data):
    """Parses a full .a7p file's bytes (32-byte hex md5 prefix + protobuf body)."""
    if len(data) < 32:
        raise A7PChecksumError("a7p: input too short for md5 prefix")
    body = data[32:]
    got = binascii.hexlify(hashlib.md5(body).digest())
    want = bytes(data[:32])
    if got != want:
        raise A7PChecksumError("a7p: md5 checksum mismatch")
    return Profile().decode(body)


def load(path):
    with open(path, "rb") as f:
        return loads(f.read())


def dumps(profile):
    """Serializes a Profile back to full .a7p file bytes (md5 prefix + body)."""
    body = profile.encode()
    hexdigest = binascii.hexlify(hashlib.md5(body).digest())
    return hexdigest + body


def dump(profile, path):
    with open(path, "wb") as f:
        f.write(dumps(profile))
