"""Zero-copy .a7p ballistic profile access for MicroPython.

Mirrors the load/loads/dump/dumps API of the `a7p` PyPI package (see
py/src/a7p/a7p.py), but Profile never builds an intermediate Python
object graph for its scalar/array fields: `_a7p._decode()` (the native
module, see src/a7p_mp.c) writes nanopb's parsed profedit_Payload
directly into Profile._buf, and Profile._s is a uctypes struct overlaid
on that same bytearray, so `profile.profile.zero_x` reads/writes the
exact memory nanopb will later re-encode from.

`_a7p` resolves two different ways depending on build mode, both wired up
so the rest of this file never has to care which one it's running under:

  - usermod: a real, separately compiled C module (see
    usermod/a7p/a7p_mod.c) -- `import _a7p` finds it normally.
  - natmod: a7p_mp.c's native part and this file are merged into a single
    a7p.mpy (see natmod/Makefile's SRC), so there's no separate `_a7p` to
    import at all -- the native part's mpy_init() runs first and leaves
    its functions as bare globals (_decode, _encode, _validate, _clamp,
    _md5) in this same module's namespace (see docs/develop/natmod.rst
    "Defining a native module"), and the `except ImportError` below
    wraps those into a synthetic `_a7p` namespace instead.

The uctypes layout constants below (PAYLOAD_SIZE, PAYLOAD_DESC,
PROFILE_STRINGS, PAYLOAD_PROFILE_OFFSET) are generated by
tools/gen_layout.py, which rewrites everything between the BEGIN/END
GENERATED markers in place -- re-run it after regenerating profedit.pb.h,
it does not touch the rest of this file. PAYLOAD_SIZE is deliberately only
defined here (not mirrored as a native global too, unlike the functions
above) -- it's a plain compile-time constant, so a runtime C->Python copy
of it would just be a second value that could drift out of sync.
"""

import binascii

import uctypes

try:
    import _a7p
except ImportError:
    # Merged natmod build (see natmod/Makefile) -- the native part's
    # mpy_init() populated these as bare globals of *this* module (there's
    # no separate module to import), which would otherwise leak them onto
    # `a7p` itself (visible via dir(a7p)/help(a7p)) alongside the `_a7p`
    # wrapper below. del removes them from this module's namespace once
    # wrapped, so `a7p._decode` etc no longer resolve -- only `a7p._a7p._decode`
    # does, same single access path as the usermod build.
    class _a7p:
        _decode = _decode
        _encode = _encode
        _validate = _validate
        _clamp = _clamp
        _md5 = _md5

    del _decode, _encode, _validate, _clamp, _md5


# BEGIN GENERATED (tools/gen_layout.py) -- do not edit by hand
PAYLOAD_SIZE = 3988
PROFILE_SIZE = 3984
SWPOS_SIZE = 20
COEFROW_SIZE = 8

SWPOS_DESC = {
    "c_idx": uctypes.INT32 | 0,
    "reticle_idx": uctypes.INT32 | 4,
    "zoom": uctypes.INT32 | 8,
    "distance": uctypes.INT32 | 12,
    "distance_from": uctypes.UINT32 | 16,
}

COEFROW_DESC = {
    "bc_cd": uctypes.INT32 | 0,
    "mv": uctypes.INT32 | 4,
}

# byte offset/size of the fixed char[] string fields -- sliced directly out
# of the backing bytearray (also zero-copy: bytearray slicing is a copy in
# CPython but MicroPython's bytearray supports memoryview slices; callers
# that want to mutate in place should use Profile.set_str()).
PROFILE_STRINGS = {
    "profile_name": (0, 51),
    "cartridge_name": (51, 51),
    "bullet_name": (102, 51),
    "short_name_top": (153, 9),
    "short_name_bot": (162, 9),
    "user_note": (171, 1025),
    "caliber": (3880, 51),
    "device_uuid": (3931, 51),
}

# PROFILE_DESC covers every scalar/enum field plus the three repeated
# arrays (as uctypes ARRAY-of-struct / ARRAY-of-scalar) for true zero-copy
# field access. String fields are intentionally left out of this
# descriptor -- see PROFILE_STRINGS above -- since uctypes has no
# fixed-char-array-as-str type.
PROFILE_DESC = {
    "zero_x": uctypes.INT32 | 1196,
    "zero_y": uctypes.INT32 | 1200,
    "sc_height": uctypes.INT32 | 1204,
    "r_twist": uctypes.INT32 | 1208,
    "c_muzzle_velocity": uctypes.INT32 | 1212,
    "c_zero_temperature": uctypes.INT32 | 1216,
    "c_t_coeff": uctypes.INT32 | 1220,
    "c_zero_distance_idx": uctypes.INT32 | 1224,
    "c_zero_air_temperature": uctypes.INT32 | 1228,
    "c_zero_air_pressure": uctypes.INT32 | 1232,
    "c_zero_air_humidity": uctypes.INT32 | 1236,
    "c_zero_w_pitch": uctypes.INT32 | 1240,
    "c_zero_p_temperature": uctypes.INT32 | 1244,
    "b_diameter": uctypes.INT32 | 1248,
    "b_weight": uctypes.INT32 | 1252,
    "b_length": uctypes.INT32 | 1256,
    "twist_dir": uctypes.UINT32 | 1260,
    "bc_type": uctypes.UINT32 | 1264,
    "switches_count": uctypes.UINT16 | 1268,
    "switches": (1272 | uctypes.ARRAY, 10, SWPOS_DESC),
    "distances_count": uctypes.UINT16 | 1472,
    "distances": (1476 | uctypes.ARRAY, 200 | uctypes.INT32),
    "coef_rows_count": uctypes.UINT16 | 2276,
    "coef_rows": (2280 | uctypes.ARRAY, 200, COEFROW_DESC),
}

# Payload = {has_profile: bool, profile: Profile} -- the wire envelope every
# .a7p file's protobuf body decodes into.
PAYLOAD_DESC = {
    "has_profile": uctypes.UINT8 | 0,
    "profile": (4, PROFILE_DESC),
}
PAYLOAD_PROFILE_OFFSET = 4
# END GENERATED


class A7PError(Exception):
    pass


class A7PChecksumError(A7PError):
    pass


class A7PDecodeError(A7PError):
    pass


class A7PValidationError(A7PError):
    pass


# Order must match the enum in src/a7p_validate_err.h exactly -- index 0
# ("valid") is never raised, _a7p._validate()'s return value indexes directly
# into this tuple. Thresholds referenced below come from a7p_validate.h
# (generated by tools/gen_validate.py from schema/a7p.schema.json).
_VALIDATE_MESSAGES = (
    "valid",
    "profile: has_profile is false (no profile present)",
    "zero_x: out of range",
    "zero_y: out of range",
    "sc_height: out of range",
    "r_twist: out of range",
    "twist_dir: invalid enum value",
    "c_muzzle_velocity: out of range",
    "c_zero_temperature: out of range",
    "c_t_coeff: out of range",
    "c_zero_distance_idx: out of range",
    "c_zero_air_temperature: out of range",
    "c_zero_air_pressure: out of range",
    "c_zero_air_humidity: out of range",
    "c_zero_w_pitch: out of range",
    "c_zero_p_temperature: out of range",
    "b_diameter: out of range",
    "b_weight: out of range",
    "b_length: out of range",
    "bc_type: invalid enum value",
    "coef_rows: too many rows (or none) for bc_type",
    "coef_rows[].bc_cd: out of range",
    "coef_rows[].mv: out of range for bc_type",
    "coef_rows[].mv: duplicate value (must be unique except 0)",
    "switches[].c_idx: out of range",
    "switches[].zoom: out of range",
    "switches[].reticle_idx: out of range",
    "switches[].distance: out of range",
    "switches[].distance_from: invalid enum value",
    "distances[]: out of range",
)


class Profile:
    """One .a7p payload, backed by a single fixed-size bytearray."""

    def __init__(self):
        self._buf = bytearray(PAYLOAD_SIZE)
        self._s = uctypes.struct(uctypes.addressof(self._buf), PAYLOAD_DESC, uctypes.LITTLE_ENDIAN)

    @property
    def has_profile(self):
        return bool(self._s.has_profile)

    @property
    def profile(self):
        """The nested profedit_Profile uctypes struct -- e.g.
        `profile.profile.zero_x`, `profile.profile.distances[0]`,
        `profile.profile.switches[0].zoom`, `profile.profile.coef_rows_count`.
        """
        return self._s.profile

    def get_str(self, name):
        """Reads a fixed char[] field (e.g. "profile_name", "user_note")."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        raw = bytes(self._buf[base:base + size])
        end = raw.find(b"\x00")
        if end < 0:
            end = len(raw)
        return raw[:end].decode()

    def set_str(self, name, value):
        """Writes a fixed char[] field in place (null-padded, NUL-terminated)."""
        off, size = PROFILE_STRINGS[name]
        base = PAYLOAD_PROFILE_OFFSET + off
        encoded = value.encode()
        if len(encoded) > size - 1:
            raise ValueError("a7p: %s exceeds %d bytes" % (name, size - 1))
        self._buf[base:base + size] = bytes(size)
        self._buf[base:base + len(encoded)] = encoded

    def decode(self, data):
        """Decodes a raw protobuf-encoded Payload body into this Profile."""
        if not _a7p._decode(self._buf, data):
            raise A7PDecodeError("a7p: failed to decode Payload")
        return self

    def encode(self):
        """Encodes this Profile back into a raw protobuf Payload body."""
        return _a7p._encode(self._buf)

    def validate(self):
        """Checks value bounds/enum validity/coef_rows rules from
        schema/a7p.schema.json (numeric ranges only -- string lengths and
        array counts are already enforced structurally by the fixed buffer
        and uctypes array sizes, so aren't re-checked here). Raises
        A7PValidationError on the first rule that fails; returns None.

        Note: some real .a7p files (e.g. go/assets/example.a7p) have
        distances[0] == 0, which the canonical schema's `distances[].minimum:
        100` rejects -- a known, pre-existing data/schema discrepancy (see
        docs/DESIGN-schema-unification.md), not a bug in this check.
        """
        code = _a7p._validate(self._buf)
        if code != 0:
            raise A7PValidationError("a7p: %s" % _VALIDATE_MESSAGES[code])

    def clamp(self):
        """Clamps every out-of-range numeric field validate() checks back
        into range, in place (e.g. after editing fields through a UI that
        doesn't itself enforce bounds). Returns the number of values
        changed (0 if nothing needed clamping).

        Not a substitute for validate() -- structural rules a number can't
        fix by clamping (coef_rows below its minimum item count, duplicate
        coef_rows[].mv) are left alone, and distances[0] == 0 is
        deliberately skipped since real .a7p files ship that even though
        the schema's static minimum is 100 (see validate()'s docstring).
        Call validate() afterwards if you need to confirm the result is
        fully valid.
        """
        return _a7p._clamp(self._buf)


def loads(data):
    """Parses a full .a7p file's bytes (32-byte hex md5 prefix + protobuf body)."""
    if len(data) < 32:
        raise A7PChecksumError("a7p: input too short for md5 prefix")
    body = data[32:]
    got = binascii.hexlify(_a7p._md5(body))
    want = bytes(data[:32])
    if got != want:
        raise A7PChecksumError("a7p: md5 checksum mismatch")
    return Profile().decode(body)


def load(fp):
    """Reads a .a7p file from an already-open binary file object (like json.load)."""
    return loads(fp.read())


def dumps(profile):
    """Serializes a Profile back to full .a7p file bytes (md5 prefix + body)."""
    body = profile.encode()
    hexdigest = binascii.hexlify(_a7p._md5(body))
    return hexdigest + body


def dump(profile, fp):
    """Writes a full .a7p file to an already-open binary file object (like json.dump)."""
    fp.write(dumps(profile))
