/* AUTO-GENERATED by micropython/tools/gen_validate.py -- do not edit by hand. */
/* Source: schema/a7p.schema.json -- re-run after editing it. */
#ifndef A7P_VALIDATE_H_INCLUDED
#define A7P_VALIDATE_H_INCLUDED

/* Profile scalar bounds ($defs/Profile/properties/<field>) */
#define A7P_ZERO_X_MIN (-200000)
#define A7P_ZERO_X_MAX (200000)
#define A7P_ZERO_Y_MIN (-200000)
#define A7P_ZERO_Y_MAX (200000)
#define A7P_SC_HEIGHT_MIN (-5000)
#define A7P_SC_HEIGHT_MAX (5000)
#define A7P_R_TWIST_MIN (0)
#define A7P_R_TWIST_MAX (10000)
#define A7P_C_MUZZLE_VELOCITY_MIN (100)
#define A7P_C_MUZZLE_VELOCITY_MAX (30000)
#define A7P_C_ZERO_TEMPERATURE_MIN (-100)
#define A7P_C_ZERO_TEMPERATURE_MAX (100)
#define A7P_C_T_COEFF_MIN (0)
#define A7P_C_T_COEFF_MAX (5000)
#define A7P_C_ZERO_DISTANCE_IDX_MIN (0)
#define A7P_C_ZERO_DISTANCE_IDX_MAX (255)
#define A7P_C_ZERO_AIR_TEMPERATURE_MIN (-100)
#define A7P_C_ZERO_AIR_TEMPERATURE_MAX (100)
#define A7P_C_ZERO_AIR_PRESSURE_MIN (3000)
#define A7P_C_ZERO_AIR_PRESSURE_MAX (15000)
#define A7P_C_ZERO_AIR_HUMIDITY_MIN (0)
#define A7P_C_ZERO_AIR_HUMIDITY_MAX (100)
#define A7P_C_ZERO_W_PITCH_MIN (-90)
#define A7P_C_ZERO_W_PITCH_MAX (90)
#define A7P_C_ZERO_P_TEMPERATURE_MIN (-100)
#define A7P_C_ZERO_P_TEMPERATURE_MAX (100)
#define A7P_B_DIAMETER_MIN (1)
#define A7P_B_DIAMETER_MAX (50000)
#define A7P_B_WEIGHT_MIN (10)
#define A7P_B_WEIGHT_MAX (65535)
#define A7P_B_LENGTH_MIN (10)
#define A7P_B_LENGTH_MAX (200000)

/* enum upper bounds ($defs/TwistDir, BcType, DType -- values are their
 * 0-based wire index, per profedit.pb.h) */
#define A7P_TWIST_DIR_MAX (1)
#define A7P_BC_TYPE_MAX (2)
#define A7P_DISTANCE_FROM_MAX (1)

/* SwitchProps ($defs/SwitchProps/properties) */
#define A7P_SWITCH_RETICLE_IDX_MIN (0)
#define A7P_SWITCH_RETICLE_IDX_MAX (255)
#define A7P_SWITCH_ZOOM_MIN (0)
#define A7P_SWITCH_ZOOM_MAX (6)
#define A7P_SWITCH_C_IDX_MAX (200)
#define A7P_SWITCH_C_IDX_UNUSED (255)
#define A7P_SWITCH_DISTANCE_MIN (100)
#define A7P_SWITCH_DISTANCE_MAX (300000)

/* distances[] items ($defs/Profile/properties/distances/items) */
#define A7P_DISTANCE_ITEM_MIN (100)
#define A7P_DISTANCE_ITEM_MAX (300000)

/* CoefRow.bc_cd ($defs/CoefRow/properties/bc_cd) */
#define A7P_COEF_BC_CD_MIN (0)
#define A7P_COEF_BC_CD_MAX (100000)

/* coef_rows: bounds depend on bc_type -- see the if/then/else on
 * $defs/Profile/properties/coef_rows. mv itself has no static maximum
 * (contextual only); minimum 0 always. */
#define A7P_COEF_ROWS_MIN_ITEMS (1)
#define A7P_COEF_ROWS_MAX_ITEMS_CUSTOM (200)
#define A7P_COEF_ROWS_MV_MAX_CUSTOM (100000)
#define A7P_COEF_ROWS_MAX_ITEMS_DEFAULT (5)
#define A7P_COEF_ROWS_MV_MAX_DEFAULT (30000)

#endif
