/* AUTO-GENERATED by micropython/tools/gen_layout.py -- do not edit by hand. */
#ifndef A7P_LAYOUT_H_INCLUDED
#define A7P_LAYOUT_H_INCLUDED

#include <stddef.h>

#define A7P_PAYLOAD_SIZE  3988u
#define A7P_PROFILE_SIZE  3984u
#define A7P_SWPOS_SIZE    20u
#define A7P_COEFROW_SIZE  8u

/* Guards against nanopb ever changing this layout under us (e.g. a proto
 * edit that flips pb_size_t width via PB_FIELD_32BIT). If one of these ever
 * fails, re-run gen_layout.py -- the Python uctypes view depends on these
 * exact offsets matching. */
_Static_assert(offsetof(profedit_Payload, has_profile) == 0 && sizeof(((profedit_Payload*)0)->has_profile) == 1, "A7P_CHECK_PROFEDIT_PAYLOAD_HAS_PROFILE");
_Static_assert(offsetof(profedit_Payload, profile) == 4 && sizeof(((profedit_Payload*)0)->profile) == 3984, "A7P_CHECK_PROFEDIT_PAYLOAD_PROFILE");
_Static_assert(offsetof(profedit_Profile, profile_name) == 0 && sizeof(((profedit_Profile*)0)->profile_name) == 51, "A7P_CHECK_PROFEDIT_PROFILE_PROFILE_NAME");
_Static_assert(offsetof(profedit_Profile, cartridge_name) == 51 && sizeof(((profedit_Profile*)0)->cartridge_name) == 51, "A7P_CHECK_PROFEDIT_PROFILE_CARTRIDGE_NAME");
_Static_assert(offsetof(profedit_Profile, bullet_name) == 102 && sizeof(((profedit_Profile*)0)->bullet_name) == 51, "A7P_CHECK_PROFEDIT_PROFILE_BULLET_NAME");
_Static_assert(offsetof(profedit_Profile, short_name_top) == 153 && sizeof(((profedit_Profile*)0)->short_name_top) == 9, "A7P_CHECK_PROFEDIT_PROFILE_SHORT_NAME_TOP");
_Static_assert(offsetof(profedit_Profile, short_name_bot) == 162 && sizeof(((profedit_Profile*)0)->short_name_bot) == 9, "A7P_CHECK_PROFEDIT_PROFILE_SHORT_NAME_BOT");
_Static_assert(offsetof(profedit_Profile, user_note) == 171 && sizeof(((profedit_Profile*)0)->user_note) == 1025, "A7P_CHECK_PROFEDIT_PROFILE_USER_NOTE");
_Static_assert(offsetof(profedit_Profile, zero_x) == 1196 && sizeof(((profedit_Profile*)0)->zero_x) == 4, "A7P_CHECK_PROFEDIT_PROFILE_ZERO_X");
_Static_assert(offsetof(profedit_Profile, zero_y) == 1200 && sizeof(((profedit_Profile*)0)->zero_y) == 4, "A7P_CHECK_PROFEDIT_PROFILE_ZERO_Y");
_Static_assert(offsetof(profedit_Profile, sc_height) == 1204 && sizeof(((profedit_Profile*)0)->sc_height) == 4, "A7P_CHECK_PROFEDIT_PROFILE_SC_HEIGHT");
_Static_assert(offsetof(profedit_Profile, r_twist) == 1208 && sizeof(((profedit_Profile*)0)->r_twist) == 4, "A7P_CHECK_PROFEDIT_PROFILE_R_TWIST");
_Static_assert(offsetof(profedit_Profile, c_muzzle_velocity) == 1212 && sizeof(((profedit_Profile*)0)->c_muzzle_velocity) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_MUZZLE_VELOCITY");
_Static_assert(offsetof(profedit_Profile, c_zero_temperature) == 1216 && sizeof(((profedit_Profile*)0)->c_zero_temperature) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_TEMPERATURE");
_Static_assert(offsetof(profedit_Profile, c_t_coeff) == 1220 && sizeof(((profedit_Profile*)0)->c_t_coeff) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_T_COEFF");
_Static_assert(offsetof(profedit_Profile, c_zero_distance_idx) == 1224 && sizeof(((profedit_Profile*)0)->c_zero_distance_idx) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_DISTANCE_IDX");
_Static_assert(offsetof(profedit_Profile, c_zero_air_temperature) == 1228 && sizeof(((profedit_Profile*)0)->c_zero_air_temperature) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_AIR_TEMPERATURE");
_Static_assert(offsetof(profedit_Profile, c_zero_air_pressure) == 1232 && sizeof(((profedit_Profile*)0)->c_zero_air_pressure) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_AIR_PRESSURE");
_Static_assert(offsetof(profedit_Profile, c_zero_air_humidity) == 1236 && sizeof(((profedit_Profile*)0)->c_zero_air_humidity) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_AIR_HUMIDITY");
_Static_assert(offsetof(profedit_Profile, c_zero_w_pitch) == 1240 && sizeof(((profedit_Profile*)0)->c_zero_w_pitch) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_W_PITCH");
_Static_assert(offsetof(profedit_Profile, c_zero_p_temperature) == 1244 && sizeof(((profedit_Profile*)0)->c_zero_p_temperature) == 4, "A7P_CHECK_PROFEDIT_PROFILE_C_ZERO_P_TEMPERATURE");
_Static_assert(offsetof(profedit_Profile, b_diameter) == 1248 && sizeof(((profedit_Profile*)0)->b_diameter) == 4, "A7P_CHECK_PROFEDIT_PROFILE_B_DIAMETER");
_Static_assert(offsetof(profedit_Profile, b_weight) == 1252 && sizeof(((profedit_Profile*)0)->b_weight) == 4, "A7P_CHECK_PROFEDIT_PROFILE_B_WEIGHT");
_Static_assert(offsetof(profedit_Profile, b_length) == 1256 && sizeof(((profedit_Profile*)0)->b_length) == 4, "A7P_CHECK_PROFEDIT_PROFILE_B_LENGTH");
_Static_assert(offsetof(profedit_Profile, twist_dir) == 1260 && sizeof(((profedit_Profile*)0)->twist_dir) == 4, "A7P_CHECK_PROFEDIT_PROFILE_TWIST_DIR");
_Static_assert(offsetof(profedit_Profile, bc_type) == 1264 && sizeof(((profedit_Profile*)0)->bc_type) == 4, "A7P_CHECK_PROFEDIT_PROFILE_BC_TYPE");
_Static_assert(offsetof(profedit_Profile, switches_count) == 1268 && sizeof(((profedit_Profile*)0)->switches_count) == 2, "A7P_CHECK_PROFEDIT_PROFILE_SWITCHES_COUNT");
_Static_assert(offsetof(profedit_Profile, switches) == 1272 && sizeof(((profedit_Profile*)0)->switches) == 200, "A7P_CHECK_PROFEDIT_PROFILE_SWITCHES");
_Static_assert(offsetof(profedit_Profile, distances_count) == 1472 && sizeof(((profedit_Profile*)0)->distances_count) == 2, "A7P_CHECK_PROFEDIT_PROFILE_DISTANCES_COUNT");
_Static_assert(offsetof(profedit_Profile, distances) == 1476 && sizeof(((profedit_Profile*)0)->distances) == 800, "A7P_CHECK_PROFEDIT_PROFILE_DISTANCES");
_Static_assert(offsetof(profedit_Profile, coef_rows_count) == 2276 && sizeof(((profedit_Profile*)0)->coef_rows_count) == 2, "A7P_CHECK_PROFEDIT_PROFILE_COEF_ROWS_COUNT");
_Static_assert(offsetof(profedit_Profile, coef_rows) == 2280 && sizeof(((profedit_Profile*)0)->coef_rows) == 1600, "A7P_CHECK_PROFEDIT_PROFILE_COEF_ROWS");
_Static_assert(offsetof(profedit_Profile, caliber) == 3880 && sizeof(((profedit_Profile*)0)->caliber) == 51, "A7P_CHECK_PROFEDIT_PROFILE_CALIBER");
_Static_assert(offsetof(profedit_Profile, device_uuid) == 3931 && sizeof(((profedit_Profile*)0)->device_uuid) == 51, "A7P_CHECK_PROFEDIT_PROFILE_DEVICE_UUID");
_Static_assert(offsetof(profedit_SwPos, c_idx) == 0 && sizeof(((profedit_SwPos*)0)->c_idx) == 4, "A7P_CHECK_PROFEDIT_SWPOS_C_IDX");
_Static_assert(offsetof(profedit_SwPos, reticle_idx) == 4 && sizeof(((profedit_SwPos*)0)->reticle_idx) == 4, "A7P_CHECK_PROFEDIT_SWPOS_RETICLE_IDX");
_Static_assert(offsetof(profedit_SwPos, zoom) == 8 && sizeof(((profedit_SwPos*)0)->zoom) == 4, "A7P_CHECK_PROFEDIT_SWPOS_ZOOM");
_Static_assert(offsetof(profedit_SwPos, distance) == 12 && sizeof(((profedit_SwPos*)0)->distance) == 4, "A7P_CHECK_PROFEDIT_SWPOS_DISTANCE");
_Static_assert(offsetof(profedit_SwPos, distance_from) == 16 && sizeof(((profedit_SwPos*)0)->distance_from) == 4, "A7P_CHECK_PROFEDIT_SWPOS_DISTANCE_FROM");
_Static_assert(offsetof(profedit_CoefRow, bc_cd) == 0 && sizeof(((profedit_CoefRow*)0)->bc_cd) == 4, "A7P_CHECK_PROFEDIT_COEFROW_BC_CD");
_Static_assert(offsetof(profedit_CoefRow, mv) == 4 && sizeof(((profedit_CoefRow*)0)->mv) == 4, "A7P_CHECK_PROFEDIT_COEFROW_MV");

#endif
