# AUTO-GENERATED by micropython/tools/gen_layout.py -- do not edit by hand.
import uctypes

PAYLOAD_SIZE = 3988
PROFILE_SIZE = 3984
SWPOS_SIZE = 20
COEFROW_SIZE = 8

SWPOS_DESC = {
    "c_idx": uctypes.INT32 | 0,
    "reticle_idx": uctypes.INT32 | 4,
    "zoom": uctypes.INT32 | 8,
    "distance": uctypes.INT32 | 12,
    "distance_from": uctypes.UINT32 | 16,
}

COEFROW_DESC = {
    "bc_cd": uctypes.INT32 | 0,
    "mv": uctypes.INT32 | 4,
}

# byte offset/size of the fixed char[] string fields -- sliced directly out
# of the backing bytearray (also zero-copy: bytearray slicing is a copy in
# CPython but MicroPython's bytearray supports memoryview slices; callers
# that want to mutate in place should use Profile.set_str()).
PROFILE_STRINGS = {
    "device_uuid": (3931, 51),
    "caliber": (3880, 51),
    "cartridge_name": (51, 51),
    "short_name_bot": (162, 9),
    "profile_name": (0, 51),
    "short_name_top": (153, 9),
    "user_note": (171, 1025),
    "bullet_name": (102, 51),
}

# PROFILE_DESC covers every scalar/enum field plus the three repeated
# arrays (as uctypes ARRAY-of-struct / ARRAY-of-scalar) for true zero-copy
# field access. String fields are intentionally left out of this
# descriptor -- see PROFILE_STRINGS above -- since uctypes has no
# fixed-char-array-as-str type.
PROFILE_DESC = {
    "zero_x": uctypes.INT32 | 1196,
    "zero_y": uctypes.INT32 | 1200,
    "sc_height": uctypes.INT32 | 1204,
    "r_twist": uctypes.INT32 | 1208,
    "c_muzzle_velocity": uctypes.INT32 | 1212,
    "c_zero_temperature": uctypes.INT32 | 1216,
    "c_t_coeff": uctypes.INT32 | 1220,
    "c_zero_distance_idx": uctypes.INT32 | 1224,
    "c_zero_air_temperature": uctypes.INT32 | 1228,
    "c_zero_air_pressure": uctypes.INT32 | 1232,
    "c_zero_air_humidity": uctypes.INT32 | 1236,
    "c_zero_w_pitch": uctypes.INT32 | 1240,
    "c_zero_p_temperature": uctypes.INT32 | 1244,
    "b_diameter": uctypes.INT32 | 1248,
    "b_weight": uctypes.INT32 | 1252,
    "b_length": uctypes.INT32 | 1256,
    "twist_dir": uctypes.UINT32 | 1260,
    "bc_type": uctypes.UINT32 | 1264,
    "switches_count": uctypes.UINT16 | 1268,
    "switches": (1272 | uctypes.ARRAY, 10, SWPOS_DESC),
    "distances_count": uctypes.UINT16 | 1472,
    "distances": (1476 | uctypes.ARRAY, 200 | uctypes.INT32),
    "coef_rows_count": uctypes.UINT16 | 2276,
    "coef_rows": (2280 | uctypes.ARRAY, 200, COEFROW_DESC),
}

# Payload = {has_profile: bool, profile: Profile} -- the wire envelope every
# .a7p file's protobuf body decodes into.
PAYLOAD_DESC = {
    "has_profile": uctypes.UINT8 | 0,
    "profile": (4, PROFILE_DESC),
}
PAYLOAD_PROFILE_OFFSET = 4
