/* Bounds/enum/conditional checks for a decoded profedit_Payload.
 *
 * The numeric thresholds below come from a7p_validate.h (generated by
 * tools/gen_validate.py from schema/a7p.schema.json) -- this file only
 * hand-maintains the *shape* of the rules: which fields get a plain
 * min/max check, the bc_type-conditional coef_rows bounds, and the
 * mv-unique-except-zero rule, none of which are expressible generically
 * from the schema alone (same as every other a7p language binding's
 * validator -- see schema/a7p.schema.json's own note on coef_rows:
 * "Enforce with one small hand-written check per language").
 */
#include "profedit.pb.h"
#include "a7p_validate.h"
#include "a7p_validate_err.h"

#define A7P_CHECK_RANGE(val, lo, hi, err) \
    do { if ((val) < (lo) || (val) > (hi)) return (err); } while (0)

int a7p_validate(const profedit_Payload *payload) {
    if (!payload->has_profile) {
        return A7P_ERR_NO_PROFILE;
    }
    const profedit_Profile *p = &payload->profile;

    A7P_CHECK_RANGE(p->zero_x, A7P_ZERO_X_MIN, A7P_ZERO_X_MAX, A7P_ERR_ZERO_X);
    A7P_CHECK_RANGE(p->zero_y, A7P_ZERO_Y_MIN, A7P_ZERO_Y_MAX, A7P_ERR_ZERO_Y);
    A7P_CHECK_RANGE(p->sc_height, A7P_SC_HEIGHT_MIN, A7P_SC_HEIGHT_MAX, A7P_ERR_SC_HEIGHT);
    A7P_CHECK_RANGE(p->r_twist, A7P_R_TWIST_MIN, A7P_R_TWIST_MAX, A7P_ERR_R_TWIST);
    if ((unsigned)p->twist_dir > A7P_TWIST_DIR_MAX) {
        return A7P_ERR_TWIST_DIR;
    }
    A7P_CHECK_RANGE(p->c_muzzle_velocity, A7P_C_MUZZLE_VELOCITY_MIN, A7P_C_MUZZLE_VELOCITY_MAX, A7P_ERR_C_MUZZLE_VELOCITY);
    A7P_CHECK_RANGE(p->c_zero_temperature, A7P_C_ZERO_TEMPERATURE_MIN, A7P_C_ZERO_TEMPERATURE_MAX, A7P_ERR_C_ZERO_TEMPERATURE);
    A7P_CHECK_RANGE(p->c_t_coeff, A7P_C_T_COEFF_MIN, A7P_C_T_COEFF_MAX, A7P_ERR_C_T_COEFF);
    A7P_CHECK_RANGE(p->c_zero_distance_idx, A7P_C_ZERO_DISTANCE_IDX_MIN, A7P_C_ZERO_DISTANCE_IDX_MAX, A7P_ERR_C_ZERO_DISTANCE_IDX);
    A7P_CHECK_RANGE(p->c_zero_air_temperature, A7P_C_ZERO_AIR_TEMPERATURE_MIN, A7P_C_ZERO_AIR_TEMPERATURE_MAX, A7P_ERR_C_ZERO_AIR_TEMPERATURE);
    A7P_CHECK_RANGE(p->c_zero_air_pressure, A7P_C_ZERO_AIR_PRESSURE_MIN, A7P_C_ZERO_AIR_PRESSURE_MAX, A7P_ERR_C_ZERO_AIR_PRESSURE);
    A7P_CHECK_RANGE(p->c_zero_air_humidity, A7P_C_ZERO_AIR_HUMIDITY_MIN, A7P_C_ZERO_AIR_HUMIDITY_MAX, A7P_ERR_C_ZERO_AIR_HUMIDITY);
    A7P_CHECK_RANGE(p->c_zero_w_pitch, A7P_C_ZERO_W_PITCH_MIN, A7P_C_ZERO_W_PITCH_MAX, A7P_ERR_C_ZERO_W_PITCH);
    A7P_CHECK_RANGE(p->c_zero_p_temperature, A7P_C_ZERO_P_TEMPERATURE_MIN, A7P_C_ZERO_P_TEMPERATURE_MAX, A7P_ERR_C_ZERO_P_TEMPERATURE);
    A7P_CHECK_RANGE(p->b_diameter, A7P_B_DIAMETER_MIN, A7P_B_DIAMETER_MAX, A7P_ERR_B_DIAMETER);
    A7P_CHECK_RANGE(p->b_weight, A7P_B_WEIGHT_MIN, A7P_B_WEIGHT_MAX, A7P_ERR_B_WEIGHT);
    A7P_CHECK_RANGE(p->b_length, A7P_B_LENGTH_MIN, A7P_B_LENGTH_MAX, A7P_ERR_B_LENGTH);
    if ((unsigned)p->bc_type > A7P_BC_TYPE_MAX) {
        return A7P_ERR_BC_TYPE;
    }

    /* coef_rows: item count and each row's mv range depend on bc_type */
    {
        int is_custom = (p->bc_type == profedit_GType_CUSTOM);
        pb_size_t max_items = is_custom ? A7P_COEF_ROWS_MAX_ITEMS_CUSTOM : A7P_COEF_ROWS_MAX_ITEMS_DEFAULT;
        int32_t mv_max = is_custom ? A7P_COEF_ROWS_MV_MAX_CUSTOM : A7P_COEF_ROWS_MV_MAX_DEFAULT;
        if (p->coef_rows_count < A7P_COEF_ROWS_MIN_ITEMS || p->coef_rows_count > max_items) {
            return A7P_ERR_COEF_ROWS_COUNT;
        }
        for (pb_size_t i = 0; i < p->coef_rows_count; i++) {
            const profedit_CoefRow *row = &p->coef_rows[i];
            A7P_CHECK_RANGE(row->bc_cd, A7P_COEF_BC_CD_MIN, A7P_COEF_BC_CD_MAX, A7P_ERR_COEF_ROWS_BC_CD_RANGE);
            if (row->mv < 0 || row->mv > mv_max) {
                return A7P_ERR_COEF_ROWS_MV_RANGE;
            }
            /* mv unique except sentinel 0 -- O(n^2), fine for n <= 200 */
            if (row->mv != 0) {
                for (pb_size_t j = 0; j < i; j++) {
                    if (p->coef_rows[j].mv == row->mv) {
                        return A7P_ERR_COEF_ROWS_MV_DUPLICATE;
                    }
                }
            }
        }
    }

    /* switches */
    for (pb_size_t i = 0; i < p->switches_count; i++) {
        const profedit_SwPos *sw = &p->switches[i];
        if (!(sw->c_idx == A7P_SWITCH_C_IDX_UNUSED ||
              (sw->c_idx >= 0 && sw->c_idx <= A7P_SWITCH_C_IDX_MAX))) {
            return A7P_ERR_SWITCHES_C_IDX;
        }
        A7P_CHECK_RANGE(sw->zoom, A7P_SWITCH_ZOOM_MIN, A7P_SWITCH_ZOOM_MAX, A7P_ERR_SWITCHES_ZOOM);
        A7P_CHECK_RANGE(sw->reticle_idx, A7P_SWITCH_RETICLE_IDX_MIN, A7P_SWITCH_RETICLE_IDX_MAX, A7P_ERR_SWITCHES_RETICLE_IDX);
        if (!(sw->distance == 0 ||
              (sw->distance >= A7P_SWITCH_DISTANCE_MIN && sw->distance <= A7P_SWITCH_DISTANCE_MAX))) {
            return A7P_ERR_SWITCHES_DISTANCE;
        }
        if ((unsigned)sw->distance_from > A7P_DISTANCE_FROM_MAX) {
            return A7P_ERR_SWITCHES_DISTANCE_FROM;
        }
    }

    /* distances[] -- note: unlike everything else here, real-world data is
     * known to violate this one (distances[0] == 0 in go/assets/example.a7p
     * and friends) -- see docs/DESIGN-schema-unification.md. Not a bug in
     * this check; callers that need to tolerate that should catch
     * A7P_ERR_DISTANCES_RANGE specifically. */
    for (pb_size_t i = 0; i < p->distances_count; i++) {
        A7P_CHECK_RANGE(p->distances[i], A7P_DISTANCE_ITEM_MIN, A7P_DISTANCE_ITEM_MAX, A7P_ERR_DISTANCES_RANGE);
    }

    return A7P_VALID;
}
