/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "profedit.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(profedit_Payload, profedit_Payload, 2)


PB_BIND(profedit_CoefRow, profedit_CoefRow, AUTO)


PB_BIND(profedit_SwPos, profedit_SwPos, AUTO)


PB_BIND(profedit_Profile, profedit_Profile, 2)
