#!/usr/bin/env python3
"""Regenerates micropython/src/a7p_validate.h from schema/a7p.schema.json.

This is *not* a generic "JSON Schema -> C" compiler -- none of py/js/dart/go
have one of those either (even go's `santhosh-tekuri/jsonschema` is a
runtime engine, not codegen; see docs/DESIGN-schema-unification.md). It's a
narrow extractor for the specific facts micropython/src/a7p_validate.c's
hand-written checks need: numeric min/max per field, valid enum ranges, and
the two thresholds the coef_rows if/then conditional branches on. The
*shape* of that conditional, and the x-unique-except-zero mv-uniqueness
rule, aren't expressible generically in any language's binding here (the
schema says as much: "Enforce with one small hand-written check per
language") -- gen_validate.py only keeps the numbers in sync with
schema/a7p.schema.json; a7p_validate.c's logic is maintained by hand, same
as py/js/dart/go's own validators.

Usage: python3 micropython/tools/gen_validate.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MICROPYTHON_DIR = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(MICROPYTHON_DIR)
SCHEMA_PATH = os.path.join(REPO_ROOT, "schema", "a7p.schema.json")
HEADER_PATH = os.path.join(MICROPYTHON_DIR, "src", "a7p_validate.h")

PROFILE_RANGE_FIELDS = [
    "zero_x", "zero_y", "sc_height", "r_twist", "c_muzzle_velocity",
    "c_zero_temperature", "c_t_coeff", "c_zero_distance_idx",
    "c_zero_air_temperature", "c_zero_air_pressure", "c_zero_air_humidity",
    "c_zero_w_pitch", "c_zero_p_temperature", "b_diameter", "b_weight",
    "b_length",
]


def main():
    with open(SCHEMA_PATH) as f:
        schema = json.load(f)
    defs = schema["$defs"]
    profile = defs["Profile"]["properties"]
    switch = defs["SwitchProps"]["properties"]
    coefrow = defs["CoefRow"]["properties"]
    coef_rows = profile["coef_rows"]

    out = []
    out.append("/* AUTO-GENERATED by micropython/tools/gen_validate.py -- do not edit by hand. */")
    out.append("/* Source: schema/a7p.schema.json -- re-run after editing it. */")
    out.append("#ifndef A7P_VALIDATE_H_INCLUDED")
    out.append("#define A7P_VALIDATE_H_INCLUDED")
    out.append("")
    out.append("/* Profile scalar bounds ($defs/Profile/properties/<field>) */")
    for name in PROFILE_RANGE_FIELDS:
        v = profile[name]
        macro = name.upper()
        out.append(f"#define A7P_{macro}_MIN ({v['minimum']})")
        out.append(f"#define A7P_{macro}_MAX ({v['maximum']})")
    out.append("")

    out.append("/* enum upper bounds ($defs/TwistDir, BcType, DType -- values are their")
    out.append(" * 0-based wire index, per profedit.pb.h) */")
    out.append(f"#define A7P_TWIST_DIR_MAX ({len(defs['TwistDir']['enum']) - 1})")
    out.append(f"#define A7P_BC_TYPE_MAX ({len(defs['BcType']['enum']) - 1})")
    out.append(f"#define A7P_DISTANCE_FROM_MAX ({len(defs['DistanceFrom']['enum']) - 1})")
    out.append("")

    out.append("/* SwitchProps ($defs/SwitchProps/properties) */")
    out.append(f"#define A7P_SWITCH_RETICLE_IDX_MIN ({switch['reticle_idx']['minimum']})")
    out.append(f"#define A7P_SWITCH_RETICLE_IDX_MAX ({switch['reticle_idx']['maximum']})")
    out.append(f"#define A7P_SWITCH_ZOOM_MIN ({switch['zoom']['minimum']})")
    out.append(f"#define A7P_SWITCH_ZOOM_MAX ({switch['zoom']['maximum']})")
    # c_idx: oneOf [0..200, const 255]; distance: oneOf [const 0, 100..300000]
    c_idx_range = next(o for o in switch["c_idx"]["oneOf"] if "minimum" in o)
    c_idx_sentinel = next(o for o in switch["c_idx"]["oneOf"] if "const" in o)
    dist_range = next(o for o in switch["distance"]["oneOf"] if "minimum" in o)
    out.append(f"#define A7P_SWITCH_C_IDX_MAX ({c_idx_range['maximum']})")
    out.append(f"#define A7P_SWITCH_C_IDX_UNUSED ({c_idx_sentinel['const']})")
    out.append(f"#define A7P_SWITCH_DISTANCE_MIN ({dist_range['minimum']})")
    out.append(f"#define A7P_SWITCH_DISTANCE_MAX ({dist_range['maximum']})")
    out.append("")

    out.append("/* distances[] items ($defs/Profile/properties/distances/items) */")
    ditems = profile["distances"]["items"]
    out.append(f"#define A7P_DISTANCE_ITEM_MIN ({ditems['minimum']})")
    out.append(f"#define A7P_DISTANCE_ITEM_MAX ({ditems['maximum']})")
    out.append("")

    out.append("/* CoefRow.bc_cd ($defs/CoefRow/properties/bc_cd) */")
    out.append(f"#define A7P_COEF_BC_CD_MIN ({coefrow['bc_cd']['minimum']})")
    out.append(f"#define A7P_COEF_BC_CD_MAX ({coefrow['bc_cd']['maximum']})")
    out.append("")

    out.append("/* coef_rows: bounds depend on bc_type -- see the if/then/else on")
    out.append(" * $defs/Profile/properties/coef_rows. mv itself has no static maximum")
    out.append(" * (contextual only); minimum 0 always. */")
    out.append(f"#define A7P_COEF_ROWS_MIN_ITEMS ({coef_rows['minItems']})")
    out.append(f"#define A7P_COEF_ROWS_MAX_ITEMS_CUSTOM ({coef_rows['then']['maxItems']})")
    out.append(f"#define A7P_COEF_ROWS_MV_MAX_CUSTOM ({coef_rows['then']['items']['properties']['mv']['maximum']})")
    out.append(f"#define A7P_COEF_ROWS_MAX_ITEMS_DEFAULT ({coef_rows['else']['maxItems']})")
    out.append(f"#define A7P_COEF_ROWS_MV_MAX_DEFAULT ({coef_rows['else']['items']['properties']['mv']['maximum']})")
    out.append("")
    out.append("#endif")

    with open(HEADER_PATH, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {HEADER_PATH}")


if __name__ == "__main__":
    main()
