// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: profedit/profedit_validate.proto

package profedit

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DType int32

const (
	DType_VALUE DType = 0
	DType_INDEX DType = 1
)

// Enum value maps for DType.
var (
	DType_name = map[int32]string{
		0: "VALUE",
		1: "INDEX",
	}
	DType_value = map[string]int32{
		"VALUE": 0,
		"INDEX": 1,
	}
)

func (x DType) Enum() *DType {
	p := new(DType)
	*p = x
	return p
}

func (x DType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DType) Descriptor() protoreflect.EnumDescriptor {
	return file_profedit_profedit_validate_proto_enumTypes[0].Descriptor()
}

func (DType) Type() protoreflect.EnumType {
	return &file_profedit_profedit_validate_proto_enumTypes[0]
}

func (x DType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DType.Descriptor instead.
func (DType) EnumDescriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{0}
}

type GType int32

const (
	GType_G1     GType = 0
	GType_G7     GType = 1
	GType_CUSTOM GType = 2
)

// Enum value maps for GType.
var (
	GType_name = map[int32]string{
		0: "G1",
		1: "G7",
		2: "CUSTOM",
	}
	GType_value = map[string]int32{
		"G1":     0,
		"G7":     1,
		"CUSTOM": 2,
	}
)

func (x GType) Enum() *GType {
	p := new(GType)
	*p = x
	return p
}

func (x GType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GType) Descriptor() protoreflect.EnumDescriptor {
	return file_profedit_profedit_validate_proto_enumTypes[1].Descriptor()
}

func (GType) Type() protoreflect.EnumType {
	return &file_profedit_profedit_validate_proto_enumTypes[1]
}

func (x GType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GType.Descriptor instead.
func (GType) EnumDescriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{1}
}

type TwistDir int32

const (
	TwistDir_RIGHT TwistDir = 0
	TwistDir_LEFT  TwistDir = 1
)

// Enum value maps for TwistDir.
var (
	TwistDir_name = map[int32]string{
		0: "RIGHT",
		1: "LEFT",
	}
	TwistDir_value = map[string]int32{
		"RIGHT": 0,
		"LEFT":  1,
	}
)

func (x TwistDir) Enum() *TwistDir {
	p := new(TwistDir)
	*p = x
	return p
}

func (x TwistDir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TwistDir) Descriptor() protoreflect.EnumDescriptor {
	return file_profedit_profedit_validate_proto_enumTypes[2].Descriptor()
}

func (TwistDir) Type() protoreflect.EnumType {
	return &file_profedit_profedit_validate_proto_enumTypes[2]
}

func (x TwistDir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TwistDir.Descriptor instead.
func (TwistDir) EnumDescriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{2}
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_profedit_profedit_validate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_profedit_profedit_validate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CoefRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BcCd          int32                  `protobuf:"varint,1,opt,name=bc_cd,json=bcCd,proto3" json:"bc_cd,omitempty"`
	Mv            int32                  `protobuf:"varint,2,opt,name=mv,proto3" json:"mv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoefRow) Reset() {
	*x = CoefRow{}
	mi := &file_profedit_profedit_validate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoefRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoefRow) ProtoMessage() {}

func (x *CoefRow) ProtoReflect() protoreflect.Message {
	mi := &file_profedit_profedit_validate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoefRow.ProtoReflect.Descriptor instead.
func (*CoefRow) Descriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{1}
}

func (x *CoefRow) GetBcCd() int32 {
	if x != nil {
		return x.BcCd
	}
	return 0
}

func (x *CoefRow) GetMv() int32 {
	if x != nil {
		return x.Mv
	}
	return 0
}

type SwPos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CIdx          int32                  `protobuf:"varint,1,opt,name=c_idx,json=cIdx,proto3" json:"c_idx,omitempty"`
	ReticleIdx    int32                  `protobuf:"varint,2,opt,name=reticle_idx,json=reticleIdx,proto3" json:"reticle_idx,omitempty"`
	Zoom          int32                  `protobuf:"varint,3,opt,name=zoom,proto3" json:"zoom,omitempty"`
	Distance      int32                  `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	DistanceFrom  DType                  `protobuf:"varint,5,opt,name=distance_from,json=distanceFrom,proto3,enum=profedit.DType" json:"distance_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwPos) Reset() {
	*x = SwPos{}
	mi := &file_profedit_profedit_validate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwPos) ProtoMessage() {}

func (x *SwPos) ProtoReflect() protoreflect.Message {
	mi := &file_profedit_profedit_validate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwPos.ProtoReflect.Descriptor instead.
func (*SwPos) Descriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{2}
}

func (x *SwPos) GetCIdx() int32 {
	if x != nil {
		return x.CIdx
	}
	return 0
}

func (x *SwPos) GetReticleIdx() int32 {
	if x != nil {
		return x.ReticleIdx
	}
	return 0
}

func (x *SwPos) GetZoom() int32 {
	if x != nil {
		return x.Zoom
	}
	return 0
}

func (x *SwPos) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SwPos) GetDistanceFrom() DType {
	if x != nil {
		return x.DistanceFrom
	}
	return DType_VALUE
}

type Profile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProfileName         string                 `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	CartridgeName       string                 `protobuf:"bytes,2,opt,name=cartridge_name,json=cartridgeName,proto3" json:"cartridge_name,omitempty"`
	BulletName          string                 `protobuf:"bytes,3,opt,name=bullet_name,json=bulletName,proto3" json:"bullet_name,omitempty"`
	ShortNameTop        string                 `protobuf:"bytes,4,opt,name=short_name_top,json=shortNameTop,proto3" json:"short_name_top,omitempty"`
	ShortNameBot        string                 `protobuf:"bytes,5,opt,name=short_name_bot,json=shortNameBot,proto3" json:"short_name_bot,omitempty"`
	UserNote            string                 `protobuf:"bytes,6,opt,name=user_note,json=userNote,proto3" json:"user_note,omitempty"`
	ZeroX               int32                  `protobuf:"varint,7,opt,name=zero_x,json=zeroX,proto3" json:"zero_x,omitempty"`
	ZeroY               int32                  `protobuf:"varint,8,opt,name=zero_y,json=zeroY,proto3" json:"zero_y,omitempty"`
	ScHeight            int32                  `protobuf:"varint,9,opt,name=sc_height,json=scHeight,proto3" json:"sc_height,omitempty"`
	RTwist              int32                  `protobuf:"varint,10,opt,name=r_twist,json=rTwist,proto3" json:"r_twist,omitempty"`
	CMuzzleVelocity     int32                  `protobuf:"varint,11,opt,name=c_muzzle_velocity,json=cMuzzleVelocity,proto3" json:"c_muzzle_velocity,omitempty"`
	CZeroTemperature    int32                  `protobuf:"varint,12,opt,name=c_zero_temperature,json=cZeroTemperature,proto3" json:"c_zero_temperature,omitempty"`
	CTCoeff             int32                  `protobuf:"varint,13,opt,name=c_t_coeff,json=cTCoeff,proto3" json:"c_t_coeff,omitempty"`
	CZeroDistanceIdx    int32                  `protobuf:"varint,14,opt,name=c_zero_distance_idx,json=cZeroDistanceIdx,proto3" json:"c_zero_distance_idx,omitempty"`
	CZeroAirTemperature int32                  `protobuf:"varint,15,opt,name=c_zero_air_temperature,json=cZeroAirTemperature,proto3" json:"c_zero_air_temperature,omitempty"`
	CZeroAirPressure    int32                  `protobuf:"varint,16,opt,name=c_zero_air_pressure,json=cZeroAirPressure,proto3" json:"c_zero_air_pressure,omitempty"`
	CZeroAirHumidity    int32                  `protobuf:"varint,17,opt,name=c_zero_air_humidity,json=cZeroAirHumidity,proto3" json:"c_zero_air_humidity,omitempty"`
	CZeroWPitch         int32                  `protobuf:"varint,18,opt,name=c_zero_w_pitch,json=cZeroWPitch,proto3" json:"c_zero_w_pitch,omitempty"`
	CZeroPTemperature   int32                  `protobuf:"varint,19,opt,name=c_zero_p_temperature,json=cZeroPTemperature,proto3" json:"c_zero_p_temperature,omitempty"`
	BDiameter           int32                  `protobuf:"varint,20,opt,name=b_diameter,json=bDiameter,proto3" json:"b_diameter,omitempty"`
	BWeight             int32                  `protobuf:"varint,21,opt,name=b_weight,json=bWeight,proto3" json:"b_weight,omitempty"`
	BLength             int32                  `protobuf:"varint,22,opt,name=b_length,json=bLength,proto3" json:"b_length,omitempty"`
	TwistDir            TwistDir               `protobuf:"varint,23,opt,name=twist_dir,json=twistDir,proto3,enum=profedit.TwistDir" json:"twist_dir,omitempty"`
	BcType              GType                  `protobuf:"varint,24,opt,name=bc_type,json=bcType,proto3,enum=profedit.GType" json:"bc_type,omitempty"`
	Switches            []*SwPos               `protobuf:"bytes,25,rep,name=switches,proto3" json:"switches,omitempty"`
	Distances           []int32                `protobuf:"varint,26,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	CoefRows            []*CoefRow             `protobuf:"bytes,27,rep,name=coef_rows,json=coefRows,proto3" json:"coef_rows,omitempty"` //each row must be unique( in a sense that no mv duplicates should be present)
	Caliber             string                 `protobuf:"bytes,28,opt,name=caliber,proto3" json:"caliber,omitempty"`
	DeviceUuid          string                 `protobuf:"bytes,29,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profedit_profedit_validate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profedit_profedit_validate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profedit_profedit_validate_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *Profile) GetCartridgeName() string {
	if x != nil {
		return x.CartridgeName
	}
	return ""
}

func (x *Profile) GetBulletName() string {
	if x != nil {
		return x.BulletName
	}
	return ""
}

func (x *Profile) GetShortNameTop() string {
	if x != nil {
		return x.ShortNameTop
	}
	return ""
}

func (x *Profile) GetShortNameBot() string {
	if x != nil {
		return x.ShortNameBot
	}
	return ""
}

func (x *Profile) GetUserNote() string {
	if x != nil {
		return x.UserNote
	}
	return ""
}

func (x *Profile) GetZeroX() int32 {
	if x != nil {
		return x.ZeroX
	}
	return 0
}

func (x *Profile) GetZeroY() int32 {
	if x != nil {
		return x.ZeroY
	}
	return 0
}

func (x *Profile) GetScHeight() int32 {
	if x != nil {
		return x.ScHeight
	}
	return 0
}

func (x *Profile) GetRTwist() int32 {
	if x != nil {
		return x.RTwist
	}
	return 0
}

func (x *Profile) GetCMuzzleVelocity() int32 {
	if x != nil {
		return x.CMuzzleVelocity
	}
	return 0
}

func (x *Profile) GetCZeroTemperature() int32 {
	if x != nil {
		return x.CZeroTemperature
	}
	return 0
}

func (x *Profile) GetCTCoeff() int32 {
	if x != nil {
		return x.CTCoeff
	}
	return 0
}

func (x *Profile) GetCZeroDistanceIdx() int32 {
	if x != nil {
		return x.CZeroDistanceIdx
	}
	return 0
}

func (x *Profile) GetCZeroAirTemperature() int32 {
	if x != nil {
		return x.CZeroAirTemperature
	}
	return 0
}

func (x *Profile) GetCZeroAirPressure() int32 {
	if x != nil {
		return x.CZeroAirPressure
	}
	return 0
}

func (x *Profile) GetCZeroAirHumidity() int32 {
	if x != nil {
		return x.CZeroAirHumidity
	}
	return 0
}

func (x *Profile) GetCZeroWPitch() int32 {
	if x != nil {
		return x.CZeroWPitch
	}
	return 0
}

func (x *Profile) GetCZeroPTemperature() int32 {
	if x != nil {
		return x.CZeroPTemperature
	}
	return 0
}

func (x *Profile) GetBDiameter() int32 {
	if x != nil {
		return x.BDiameter
	}
	return 0
}

func (x *Profile) GetBWeight() int32 {
	if x != nil {
		return x.BWeight
	}
	return 0
}

func (x *Profile) GetBLength() int32 {
	if x != nil {
		return x.BLength
	}
	return 0
}

func (x *Profile) GetTwistDir() TwistDir {
	if x != nil {
		return x.TwistDir
	}
	return TwistDir_RIGHT
}

func (x *Profile) GetBcType() GType {
	if x != nil {
		return x.BcType
	}
	return GType_G1
}

func (x *Profile) GetSwitches() []*SwPos {
	if x != nil {
		return x.Switches
	}
	return nil
}

func (x *Profile) GetDistances() []int32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *Profile) GetCoefRows() []*CoefRow {
	if x != nil {
		return x.CoefRows
	}
	return nil
}

func (x *Profile) GetCaliber() string {
	if x != nil {
		return x.Caliber
	}
	return ""
}

func (x *Profile) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

var File_profedit_profedit_validate_proto protoreflect.FileDescriptor

const file_profedit_profedit_validate_proto_rawDesc = "" +
	"\n" +
	" profedit/profedit_validate.proto\x12\bprofedit\x1a\x1bbuf/validate/validate.proto\"6\n" +
	"\aPayload\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.profedit.ProfileR\aprofile\".\n" +
	"\aCoefRow\x12\x13\n" +
	"\x05bc_cd\x18\x01 \x01(\x05R\x04bcCd\x12\x0e\n" +
	"\x02mv\x18\x02 \x01(\x05R\x02mv\"\xa3\x01\n" +
	"\x05SwPos\x12\x13\n" +
	"\x05c_idx\x18\x01 \x01(\x05R\x04cIdx\x12\x1f\n" +
	"\vreticle_idx\x18\x02 \x01(\x05R\n" +
	"reticleIdx\x12\x12\n" +
	"\x04zoom\x18\x03 \x01(\x05R\x04zoom\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x05R\bdistance\x124\n" +
	"\rdistance_from\x18\x05 \x01(\x0e2\x0f.profedit.DTypeR\fdistanceFrom\"\x97\v\n" +
	"\aProfile\x12*\n" +
	"\fprofile_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x182R\vprofileName\x12.\n" +
	"\x0ecartridge_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x182R\rcartridgeName\x12(\n" +
	"\vbullet_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x182R\n" +
	"bulletName\x12-\n" +
	"\x0eshort_name_top\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18\bR\fshortNameTop\x12-\n" +
	"\x0eshort_name_bot\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18\bR\fshortNameBot\x12%\n" +
	"\tuser_note\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xfa\x01R\buserNote\x12+\n" +
	"\x06zero_x\x18\a \x01(\x05B\x14\xbaH\x11\x1a\x0f\x18\xc0\xcf$(\xc0\xb0\xdb\xff\xff\xff\xff\xff\xff\x01R\x05zeroX\x12+\n" +
	"\x06zero_y\x18\b \x01(\x05B\x14\xbaH\x11\x1a\x0f\x18\xc0\xcf$(\xc0\xb0\xdb\xff\xff\xff\xff\xff\xff\x01R\x05zeroY\x120\n" +
	"\tsc_height\x18\t \x01(\x05B\x13\xbaH\x10\x1a\x0e\x18\x88'(\xf8\xd8\xff\xff\xff\xff\xff\xff\xff\x01R\bscHeight\x12#\n" +
	"\ar_twist\x18\n" +
	" \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90N(\x00R\x06rTwist\x127\n" +
	"\x11c_muzzle_velocity\x18\v \x01(\x05B\v\xbaH\b\x1a\x06\x18\xb0\xea\x01(dR\x0fcMuzzleVelocity\x12@\n" +
	"\x12c_zero_temperature\x18\f \x01(\x05B\x12\xbaH\x0f\x1a\r\x18d(\x9c\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x10cZeroTemperature\x12&\n" +
	"\tc_t_coeff\x18\r \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xb8\x17(\x02R\acTCoeff\x129\n" +
	"\x13c_zero_distance_idx\x18\x0e \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x10\xc8\x01(\x00R\x10cZeroDistanceIdx\x12G\n" +
	"\x16c_zero_air_temperature\x18\x0f \x01(\x05B\x12\xbaH\x0f\x1a\r\x18d(\x9c\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x13cZeroAirTemperature\x12-\n" +
	"\x13c_zero_air_pressure\x18\x10 \x01(\x05R\x10cZeroAirPressure\x128\n" +
	"\x13c_zero_air_humidity\x18\x11 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\x10cZeroAirHumidity\x127\n" +
	"\x0ec_zero_w_pitch\x18\x12 \x01(\x05B\x12\xbaH\x0f\x1a\r\x18Z(\xa6\xff\xff\xff\xff\xff\xff\xff\xff\x01R\vcZeroWPitch\x12C\n" +
	"\x14c_zero_p_temperature\x18\x13 \x01(\x05B\x12\xbaH\x0f\x1a\r\x18d(\x9c\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x11cZeroPTemperature\x12*\n" +
	"\n" +
	"b_diameter\x18\x14 \x01(\x05B\v\xbaH\b\x1a\x06\x18\xff\xff\x03(\x01R\tbDiameter\x12&\n" +
	"\bb_weight\x18\x15 \x01(\x05B\v\xbaH\b\x1a\x06\x18\xff\xff\x03(\n" +
	"R\abWeight\x12%\n" +
	"\bb_length\x18\x16 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90N(\x01R\abLength\x12/\n" +
	"\ttwist_dir\x18\x17 \x01(\x0e2\x12.profedit.TwistDirR\btwistDir\x12(\n" +
	"\abc_type\x18\x18 \x01(\x0e2\x0f.profedit.GTypeR\x06bcType\x127\n" +
	"\bswitches\x18\x19 \x03(\v2\x0f.profedit.SwPosB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10\x04R\bswitches\x12)\n" +
	"\tdistances\x18\x1a \x03(\x05B\v\xbaH\b\x92\x01\x05\b\x04\x10\xc8\x01R\tdistances\x12;\n" +
	"\tcoef_rows\x18\x1b \x03(\v2\x11.profedit.CoefRowB\v\xbaH\b\x92\x01\x05\b\x01\x10\xc8\x01R\bcoefRows\x12!\n" +
	"\acaliber\x18\x1c \x01(\tB\a\xbaH\x04r\x02\x182R\acaliber\x12(\n" +
	"\vdevice_uuid\x18\x1d \x01(\tB\a\xbaH\x04r\x02\x182R\n" +
	"deviceUuid*\x1d\n" +
	"\x05DType\x12\t\n" +
	"\x05VALUE\x10\x00\x12\t\n" +
	"\x05INDEX\x10\x01*#\n" +
	"\x05GType\x12\x06\n" +
	"\x02G1\x10\x00\x12\x06\n" +
	"\x02G7\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02*\x1f\n" +
	"\bTwistDir\x12\t\n" +
	"\x05RIGHT\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01B2Z0github.com/jaremko/a7p_transfer_example/profeditb\x06proto3"

var (
	file_profedit_profedit_validate_proto_rawDescOnce sync.Once
	file_profedit_profedit_validate_proto_rawDescData []byte
)

func file_profedit_profedit_validate_proto_rawDescGZIP() []byte {
	file_profedit_profedit_validate_proto_rawDescOnce.Do(func() {
		file_profedit_profedit_validate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profedit_profedit_validate_proto_rawDesc), len(file_profedit_profedit_validate_proto_rawDesc)))
	})
	return file_profedit_profedit_validate_proto_rawDescData
}

var file_profedit_profedit_validate_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_profedit_profedit_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_profedit_profedit_validate_proto_goTypes = []any{
	(DType)(0),      // 0: profedit.DType
	(GType)(0),      // 1: profedit.GType
	(TwistDir)(0),   // 2: profedit.TwistDir
	(*Payload)(nil), // 3: profedit.Payload
	(*CoefRow)(nil), // 4: profedit.CoefRow
	(*SwPos)(nil),   // 5: profedit.SwPos
	(*Profile)(nil), // 6: profedit.Profile
}
var file_profedit_profedit_validate_proto_depIdxs = []int32{
	6, // 0: profedit.Payload.profile:type_name -> profedit.Profile
	0, // 1: profedit.SwPos.distance_from:type_name -> profedit.DType
	2, // 2: profedit.Profile.twist_dir:type_name -> profedit.TwistDir
	1, // 3: profedit.Profile.bc_type:type_name -> profedit.GType
	5, // 4: profedit.Profile.switches:type_name -> profedit.SwPos
	4, // 5: profedit.Profile.coef_rows:type_name -> profedit.CoefRow
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_profedit_profedit_validate_proto_init() }
func file_profedit_profedit_validate_proto_init() {
	if File_profedit_profedit_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profedit_profedit_validate_proto_rawDesc), len(file_profedit_profedit_validate_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profedit_profedit_validate_proto_goTypes,
		DependencyIndexes: file_profedit_profedit_validate_proto_depIdxs,
		EnumInfos:         file_profedit_profedit_validate_proto_enumTypes,
		MessageInfos:      file_profedit_profedit_validate_proto_msgTypes,
	}.Build()
	File_profedit_profedit_validate_proto = out.File
	file_profedit_profedit_validate_proto_goTypes = nil
	file_profedit_profedit_validate_proto_depIdxs = nil
}
