// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: profedit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "profedit";

export enum DType {
  VALUE = 0,
  INDEX = 1,
  UNRECOGNIZED = -1,
}

export function dTypeFromJSON(object: any): DType {
  switch (object) {
    case 0:
    case "VALUE":
      return DType.VALUE;
    case 1:
    case "INDEX":
      return DType.INDEX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DType.UNRECOGNIZED;
  }
}

export function dTypeToJSON(object: DType): string {
  switch (object) {
    case DType.VALUE:
      return "VALUE";
    case DType.INDEX:
      return "INDEX";
    case DType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum GType {
  G1 = 0,
  G7 = 1,
  CUSTOM = 2,
  UNRECOGNIZED = -1,
}

export function gTypeFromJSON(object: any): GType {
  switch (object) {
    case 0:
    case "G1":
      return GType.G1;
    case 1:
    case "G7":
      return GType.G7;
    case 2:
    case "CUSTOM":
      return GType.CUSTOM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GType.UNRECOGNIZED;
  }
}

export function gTypeToJSON(object: GType): string {
  switch (object) {
    case GType.G1:
      return "G1";
    case GType.G7:
      return "G7";
    case GType.CUSTOM:
      return "CUSTOM";
    case GType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TwistDir {
  RIGHT = 0,
  LEFT = 1,
  UNRECOGNIZED = -1,
}

export function twistDirFromJSON(object: any): TwistDir {
  switch (object) {
    case 0:
    case "RIGHT":
      return TwistDir.RIGHT;
    case 1:
    case "LEFT":
      return TwistDir.LEFT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TwistDir.UNRECOGNIZED;
  }
}

export function twistDirToJSON(object: TwistDir): string {
  switch (object) {
    case TwistDir.RIGHT:
      return "RIGHT";
    case TwistDir.LEFT:
      return "LEFT";
    case TwistDir.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Payload {
  profile: Profile | undefined;
}

export interface CoefRow {
  bcCd: number;
  mv: number;
}

export interface SwPos {
  cIdx: number;
  reticleIdx: number;
  zoom: number;
  distance: number;
  distanceFrom: DType;
}

export interface Profile {
  profileName: string;
  cartridgeName: string;
  bulletName: string;
  shortNameTop: string;
  shortNameBot: string;
  userNote: string;
  zeroX: number;
  zeroY: number;
  scHeight: number;
  rTwist: number;
  cMuzzleVelocity: number;
  cZeroTemperature: number;
  cTCoeff: number;
  cZeroDistanceIdx: number;
  cZeroAirTemperature: number;
  cZeroAirPressure: number;
  cZeroAirHumidity: number;
  cZeroWPitch: number;
  cZeroPTemperature: number;
  bDiameter: number;
  bWeight: number;
  bLength: number;
  twistDir: TwistDir;
  bcType: GType;
  switches: SwPos[];
  distances: number[];
  coefRows: CoefRow[];
  caliber: string;
  deviceUuid: string;
}

function createBasePayload(): Payload {
  return { profile: undefined };
}

export const Payload: MessageFns<Payload> = {
  encode(message: Payload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profile !== undefined) {
      Profile.encode(message.profile, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Payload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.profile = Profile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Payload {
    return { profile: isSet(object.profile) ? Profile.fromJSON(object.profile) : undefined };
  },

  toJSON(message: Payload): unknown {
    const obj: any = {};
    if (message.profile !== undefined) {
      obj.profile = Profile.toJSON(message.profile);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Payload>, I>>(base?: I): Payload {
    return Payload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Payload>, I>>(object: I): Payload {
    const message = createBasePayload();
    message.profile = (object.profile !== undefined && object.profile !== null)
      ? Profile.fromPartial(object.profile)
      : undefined;
    return message;
  },
};

function createBaseCoefRow(): CoefRow {
  return { bcCd: 0, mv: 0 };
}

export const CoefRow: MessageFns<CoefRow> = {
  encode(message: CoefRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bcCd !== 0) {
      writer.uint32(8).int32(message.bcCd);
    }
    if (message.mv !== 0) {
      writer.uint32(16).int32(message.mv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoefRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoefRow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bcCd = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mv = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CoefRow {
    return {
      bcCd: isSet(object.bcCd)
        ? globalThis.Number(object.bcCd)
        : isSet(object.bc_cd)
        ? globalThis.Number(object.bc_cd)
        : 0,
      mv: isSet(object.mv) ? globalThis.Number(object.mv) : 0,
    };
  },

  toJSON(message: CoefRow): unknown {
    const obj: any = {};
    if (message.bcCd !== 0) {
      obj.bcCd = Math.round(message.bcCd);
    }
    if (message.mv !== 0) {
      obj.mv = Math.round(message.mv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CoefRow>, I>>(base?: I): CoefRow {
    return CoefRow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CoefRow>, I>>(object: I): CoefRow {
    const message = createBaseCoefRow();
    message.bcCd = object.bcCd ?? 0;
    message.mv = object.mv ?? 0;
    return message;
  },
};

function createBaseSwPos(): SwPos {
  return { cIdx: 0, reticleIdx: 0, zoom: 0, distance: 0, distanceFrom: 0 };
}

export const SwPos: MessageFns<SwPos> = {
  encode(message: SwPos, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cIdx !== 0) {
      writer.uint32(8).int32(message.cIdx);
    }
    if (message.reticleIdx !== 0) {
      writer.uint32(16).int32(message.reticleIdx);
    }
    if (message.zoom !== 0) {
      writer.uint32(24).int32(message.zoom);
    }
    if (message.distance !== 0) {
      writer.uint32(32).int32(message.distance);
    }
    if (message.distanceFrom !== 0) {
      writer.uint32(40).int32(message.distanceFrom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SwPos {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSwPos();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cIdx = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reticleIdx = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.zoom = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.distance = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.distanceFrom = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SwPos {
    return {
      cIdx: isSet(object.cIdx)
        ? globalThis.Number(object.cIdx)
        : isSet(object.c_idx)
        ? globalThis.Number(object.c_idx)
        : 0,
      reticleIdx: isSet(object.reticleIdx)
        ? globalThis.Number(object.reticleIdx)
        : isSet(object.reticle_idx)
        ? globalThis.Number(object.reticle_idx)
        : 0,
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0,
      distance: isSet(object.distance) ? globalThis.Number(object.distance) : 0,
      distanceFrom: isSet(object.distanceFrom)
        ? dTypeFromJSON(object.distanceFrom)
        : isSet(object.distance_from)
        ? dTypeFromJSON(object.distance_from)
        : 0,
    };
  },

  toJSON(message: SwPos): unknown {
    const obj: any = {};
    if (message.cIdx !== 0) {
      obj.cIdx = Math.round(message.cIdx);
    }
    if (message.reticleIdx !== 0) {
      obj.reticleIdx = Math.round(message.reticleIdx);
    }
    if (message.zoom !== 0) {
      obj.zoom = Math.round(message.zoom);
    }
    if (message.distance !== 0) {
      obj.distance = Math.round(message.distance);
    }
    if (message.distanceFrom !== 0) {
      obj.distanceFrom = dTypeToJSON(message.distanceFrom);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwPos>, I>>(base?: I): SwPos {
    return SwPos.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwPos>, I>>(object: I): SwPos {
    const message = createBaseSwPos();
    message.cIdx = object.cIdx ?? 0;
    message.reticleIdx = object.reticleIdx ?? 0;
    message.zoom = object.zoom ?? 0;
    message.distance = object.distance ?? 0;
    message.distanceFrom = object.distanceFrom ?? 0;
    return message;
  },
};

function createBaseProfile(): Profile {
  return {
    profileName: "",
    cartridgeName: "",
    bulletName: "",
    shortNameTop: "",
    shortNameBot: "",
    userNote: "",
    zeroX: 0,
    zeroY: 0,
    scHeight: 0,
    rTwist: 0,
    cMuzzleVelocity: 0,
    cZeroTemperature: 0,
    cTCoeff: 0,
    cZeroDistanceIdx: 0,
    cZeroAirTemperature: 0,
    cZeroAirPressure: 0,
    cZeroAirHumidity: 0,
    cZeroWPitch: 0,
    cZeroPTemperature: 0,
    bDiameter: 0,
    bWeight: 0,
    bLength: 0,
    twistDir: 0,
    bcType: 0,
    switches: [],
    distances: [],
    coefRows: [],
    caliber: "",
    deviceUuid: "",
  };
}

export const Profile: MessageFns<Profile> = {
  encode(message: Profile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profileName !== "") {
      writer.uint32(10).string(message.profileName);
    }
    if (message.cartridgeName !== "") {
      writer.uint32(18).string(message.cartridgeName);
    }
    if (message.bulletName !== "") {
      writer.uint32(26).string(message.bulletName);
    }
    if (message.shortNameTop !== "") {
      writer.uint32(34).string(message.shortNameTop);
    }
    if (message.shortNameBot !== "") {
      writer.uint32(42).string(message.shortNameBot);
    }
    if (message.userNote !== "") {
      writer.uint32(50).string(message.userNote);
    }
    if (message.zeroX !== 0) {
      writer.uint32(56).int32(message.zeroX);
    }
    if (message.zeroY !== 0) {
      writer.uint32(64).int32(message.zeroY);
    }
    if (message.scHeight !== 0) {
      writer.uint32(72).int32(message.scHeight);
    }
    if (message.rTwist !== 0) {
      writer.uint32(80).int32(message.rTwist);
    }
    if (message.cMuzzleVelocity !== 0) {
      writer.uint32(88).int32(message.cMuzzleVelocity);
    }
    if (message.cZeroTemperature !== 0) {
      writer.uint32(96).int32(message.cZeroTemperature);
    }
    if (message.cTCoeff !== 0) {
      writer.uint32(104).int32(message.cTCoeff);
    }
    if (message.cZeroDistanceIdx !== 0) {
      writer.uint32(112).int32(message.cZeroDistanceIdx);
    }
    if (message.cZeroAirTemperature !== 0) {
      writer.uint32(120).int32(message.cZeroAirTemperature);
    }
    if (message.cZeroAirPressure !== 0) {
      writer.uint32(128).int32(message.cZeroAirPressure);
    }
    if (message.cZeroAirHumidity !== 0) {
      writer.uint32(136).int32(message.cZeroAirHumidity);
    }
    if (message.cZeroWPitch !== 0) {
      writer.uint32(144).int32(message.cZeroWPitch);
    }
    if (message.cZeroPTemperature !== 0) {
      writer.uint32(152).int32(message.cZeroPTemperature);
    }
    if (message.bDiameter !== 0) {
      writer.uint32(160).int32(message.bDiameter);
    }
    if (message.bWeight !== 0) {
      writer.uint32(168).int32(message.bWeight);
    }
    if (message.bLength !== 0) {
      writer.uint32(176).int32(message.bLength);
    }
    if (message.twistDir !== 0) {
      writer.uint32(184).int32(message.twistDir);
    }
    if (message.bcType !== 0) {
      writer.uint32(192).int32(message.bcType);
    }
    for (const v of message.switches) {
      SwPos.encode(v!, writer.uint32(202).fork()).join();
    }
    writer.uint32(210).fork();
    for (const v of message.distances) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.coefRows) {
      CoefRow.encode(v!, writer.uint32(218).fork()).join();
    }
    if (message.caliber !== "") {
      writer.uint32(226).string(message.caliber);
    }
    if (message.deviceUuid !== "") {
      writer.uint32(234).string(message.deviceUuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Profile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.profileName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cartridgeName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bulletName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.shortNameTop = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.shortNameBot = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.userNote = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.zeroX = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.zeroY = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.scHeight = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.rTwist = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.cMuzzleVelocity = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.cZeroTemperature = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.cTCoeff = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.cZeroDistanceIdx = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.cZeroAirTemperature = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.cZeroAirPressure = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.cZeroAirHumidity = reader.int32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.cZeroWPitch = reader.int32();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.cZeroPTemperature = reader.int32();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.bDiameter = reader.int32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.bWeight = reader.int32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.bLength = reader.int32();
          continue;
        }
        case 23: {
          if (tag !== 184) {
            break;
          }

          message.twistDir = reader.int32() as any;
          continue;
        }
        case 24: {
          if (tag !== 192) {
            break;
          }

          message.bcType = reader.int32() as any;
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.switches.push(SwPos.decode(reader, reader.uint32()));
          continue;
        }
        case 26: {
          if (tag === 208) {
            message.distances.push(reader.int32());

            continue;
          }

          if (tag === 210) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.distances.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.coefRows.push(CoefRow.decode(reader, reader.uint32()));
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.caliber = reader.string();
          continue;
        }
        case 29: {
          if (tag !== 234) {
            break;
          }

          message.deviceUuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Profile {
    return {
      profileName: isSet(object.profileName)
        ? globalThis.String(object.profileName)
        : isSet(object.profile_name)
        ? globalThis.String(object.profile_name)
        : "",
      cartridgeName: isSet(object.cartridgeName)
        ? globalThis.String(object.cartridgeName)
        : isSet(object.cartridge_name)
        ? globalThis.String(object.cartridge_name)
        : "",
      bulletName: isSet(object.bulletName)
        ? globalThis.String(object.bulletName)
        : isSet(object.bullet_name)
        ? globalThis.String(object.bullet_name)
        : "",
      shortNameTop: isSet(object.shortNameTop)
        ? globalThis.String(object.shortNameTop)
        : isSet(object.short_name_top)
        ? globalThis.String(object.short_name_top)
        : "",
      shortNameBot: isSet(object.shortNameBot)
        ? globalThis.String(object.shortNameBot)
        : isSet(object.short_name_bot)
        ? globalThis.String(object.short_name_bot)
        : "",
      userNote: isSet(object.userNote)
        ? globalThis.String(object.userNote)
        : isSet(object.user_note)
        ? globalThis.String(object.user_note)
        : "",
      zeroX: isSet(object.zeroX)
        ? globalThis.Number(object.zeroX)
        : isSet(object.zero_x)
        ? globalThis.Number(object.zero_x)
        : 0,
      zeroY: isSet(object.zeroY)
        ? globalThis.Number(object.zeroY)
        : isSet(object.zero_y)
        ? globalThis.Number(object.zero_y)
        : 0,
      scHeight: isSet(object.scHeight)
        ? globalThis.Number(object.scHeight)
        : isSet(object.sc_height)
        ? globalThis.Number(object.sc_height)
        : 0,
      rTwist: isSet(object.rTwist)
        ? globalThis.Number(object.rTwist)
        : isSet(object.r_twist)
        ? globalThis.Number(object.r_twist)
        : 0,
      cMuzzleVelocity: isSet(object.cMuzzleVelocity)
        ? globalThis.Number(object.cMuzzleVelocity)
        : isSet(object.c_muzzle_velocity)
        ? globalThis.Number(object.c_muzzle_velocity)
        : 0,
      cZeroTemperature: isSet(object.cZeroTemperature)
        ? globalThis.Number(object.cZeroTemperature)
        : isSet(object.c_zero_temperature)
        ? globalThis.Number(object.c_zero_temperature)
        : 0,
      cTCoeff: isSet(object.cTCoeff)
        ? globalThis.Number(object.cTCoeff)
        : isSet(object.c_t_coeff)
        ? globalThis.Number(object.c_t_coeff)
        : 0,
      cZeroDistanceIdx: isSet(object.cZeroDistanceIdx)
        ? globalThis.Number(object.cZeroDistanceIdx)
        : isSet(object.c_zero_distance_idx)
        ? globalThis.Number(object.c_zero_distance_idx)
        : 0,
      cZeroAirTemperature: isSet(object.cZeroAirTemperature)
        ? globalThis.Number(object.cZeroAirTemperature)
        : isSet(object.c_zero_air_temperature)
        ? globalThis.Number(object.c_zero_air_temperature)
        : 0,
      cZeroAirPressure: isSet(object.cZeroAirPressure)
        ? globalThis.Number(object.cZeroAirPressure)
        : isSet(object.c_zero_air_pressure)
        ? globalThis.Number(object.c_zero_air_pressure)
        : 0,
      cZeroAirHumidity: isSet(object.cZeroAirHumidity)
        ? globalThis.Number(object.cZeroAirHumidity)
        : isSet(object.c_zero_air_humidity)
        ? globalThis.Number(object.c_zero_air_humidity)
        : 0,
      cZeroWPitch: isSet(object.cZeroWPitch)
        ? globalThis.Number(object.cZeroWPitch)
        : isSet(object.c_zero_w_pitch)
        ? globalThis.Number(object.c_zero_w_pitch)
        : 0,
      cZeroPTemperature: isSet(object.cZeroPTemperature)
        ? globalThis.Number(object.cZeroPTemperature)
        : isSet(object.c_zero_p_temperature)
        ? globalThis.Number(object.c_zero_p_temperature)
        : 0,
      bDiameter: isSet(object.bDiameter)
        ? globalThis.Number(object.bDiameter)
        : isSet(object.b_diameter)
        ? globalThis.Number(object.b_diameter)
        : 0,
      bWeight: isSet(object.bWeight)
        ? globalThis.Number(object.bWeight)
        : isSet(object.b_weight)
        ? globalThis.Number(object.b_weight)
        : 0,
      bLength: isSet(object.bLength)
        ? globalThis.Number(object.bLength)
        : isSet(object.b_length)
        ? globalThis.Number(object.b_length)
        : 0,
      twistDir: isSet(object.twistDir)
        ? twistDirFromJSON(object.twistDir)
        : isSet(object.twist_dir)
        ? twistDirFromJSON(object.twist_dir)
        : 0,
      bcType: isSet(object.bcType)
        ? gTypeFromJSON(object.bcType)
        : isSet(object.bc_type)
        ? gTypeFromJSON(object.bc_type)
        : 0,
      switches: globalThis.Array.isArray(object?.switches)
        ? object.switches.map((e: any) => SwPos.fromJSON(e))
        : [],
      distances: globalThis.Array.isArray(object?.distances)
        ? object.distances.map((e: any) => globalThis.Number(e))
        : [],
      coefRows: globalThis.Array.isArray(object?.coefRows)
        ? object.coefRows.map((e: any) => CoefRow.fromJSON(e))
        : globalThis.Array.isArray(object?.coef_rows)
        ? object.coef_rows.map((e: any) => CoefRow.fromJSON(e))
        : [],
      caliber: isSet(object.caliber) ? globalThis.String(object.caliber) : "",
      deviceUuid: isSet(object.deviceUuid)
        ? globalThis.String(object.deviceUuid)
        : isSet(object.device_uuid)
        ? globalThis.String(object.device_uuid)
        : "",
    };
  },

  toJSON(message: Profile): unknown {
    const obj: any = {};
    if (message.profileName !== "") {
      obj.profileName = message.profileName;
    }
    if (message.cartridgeName !== "") {
      obj.cartridgeName = message.cartridgeName;
    }
    if (message.bulletName !== "") {
      obj.bulletName = message.bulletName;
    }
    if (message.shortNameTop !== "") {
      obj.shortNameTop = message.shortNameTop;
    }
    if (message.shortNameBot !== "") {
      obj.shortNameBot = message.shortNameBot;
    }
    if (message.userNote !== "") {
      obj.userNote = message.userNote;
    }
    if (message.zeroX !== 0) {
      obj.zeroX = Math.round(message.zeroX);
    }
    if (message.zeroY !== 0) {
      obj.zeroY = Math.round(message.zeroY);
    }
    if (message.scHeight !== 0) {
      obj.scHeight = Math.round(message.scHeight);
    }
    if (message.rTwist !== 0) {
      obj.rTwist = Math.round(message.rTwist);
    }
    if (message.cMuzzleVelocity !== 0) {
      obj.cMuzzleVelocity = Math.round(message.cMuzzleVelocity);
    }
    if (message.cZeroTemperature !== 0) {
      obj.cZeroTemperature = Math.round(message.cZeroTemperature);
    }
    if (message.cTCoeff !== 0) {
      obj.cTCoeff = Math.round(message.cTCoeff);
    }
    if (message.cZeroDistanceIdx !== 0) {
      obj.cZeroDistanceIdx = Math.round(message.cZeroDistanceIdx);
    }
    if (message.cZeroAirTemperature !== 0) {
      obj.cZeroAirTemperature = Math.round(message.cZeroAirTemperature);
    }
    if (message.cZeroAirPressure !== 0) {
      obj.cZeroAirPressure = Math.round(message.cZeroAirPressure);
    }
    if (message.cZeroAirHumidity !== 0) {
      obj.cZeroAirHumidity = Math.round(message.cZeroAirHumidity);
    }
    if (message.cZeroWPitch !== 0) {
      obj.cZeroWPitch = Math.round(message.cZeroWPitch);
    }
    if (message.cZeroPTemperature !== 0) {
      obj.cZeroPTemperature = Math.round(message.cZeroPTemperature);
    }
    if (message.bDiameter !== 0) {
      obj.bDiameter = Math.round(message.bDiameter);
    }
    if (message.bWeight !== 0) {
      obj.bWeight = Math.round(message.bWeight);
    }
    if (message.bLength !== 0) {
      obj.bLength = Math.round(message.bLength);
    }
    if (message.twistDir !== 0) {
      obj.twistDir = twistDirToJSON(message.twistDir);
    }
    if (message.bcType !== 0) {
      obj.bcType = gTypeToJSON(message.bcType);
    }
    if (message.switches?.length) {
      obj.switches = message.switches.map((e) => SwPos.toJSON(e));
    }
    if (message.distances?.length) {
      obj.distances = message.distances.map((e) => Math.round(e));
    }
    if (message.coefRows?.length) {
      obj.coefRows = message.coefRows.map((e) => CoefRow.toJSON(e));
    }
    if (message.caliber !== "") {
      obj.caliber = message.caliber;
    }
    if (message.deviceUuid !== "") {
      obj.deviceUuid = message.deviceUuid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Profile>, I>>(base?: I): Profile {
    return Profile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Profile>, I>>(object: I): Profile {
    const message = createBaseProfile();
    message.profileName = object.profileName ?? "";
    message.cartridgeName = object.cartridgeName ?? "";
    message.bulletName = object.bulletName ?? "";
    message.shortNameTop = object.shortNameTop ?? "";
    message.shortNameBot = object.shortNameBot ?? "";
    message.userNote = object.userNote ?? "";
    message.zeroX = object.zeroX ?? 0;
    message.zeroY = object.zeroY ?? 0;
    message.scHeight = object.scHeight ?? 0;
    message.rTwist = object.rTwist ?? 0;
    message.cMuzzleVelocity = object.cMuzzleVelocity ?? 0;
    message.cZeroTemperature = object.cZeroTemperature ?? 0;
    message.cTCoeff = object.cTCoeff ?? 0;
    message.cZeroDistanceIdx = object.cZeroDistanceIdx ?? 0;
    message.cZeroAirTemperature = object.cZeroAirTemperature ?? 0;
    message.cZeroAirPressure = object.cZeroAirPressure ?? 0;
    message.cZeroAirHumidity = object.cZeroAirHumidity ?? 0;
    message.cZeroWPitch = object.cZeroWPitch ?? 0;
    message.cZeroPTemperature = object.cZeroPTemperature ?? 0;
    message.bDiameter = object.bDiameter ?? 0;
    message.bWeight = object.bWeight ?? 0;
    message.bLength = object.bLength ?? 0;
    message.twistDir = object.twistDir ?? 0;
    message.bcType = object.bcType ?? 0;
    message.switches = object.switches?.map((e) => SwPos.fromPartial(e)) || [];
    message.distances = object.distances?.map((e) => e) || [];
    message.coefRows = object.coefRows?.map((e) => CoefRow.fromPartial(e)) || [];
    message.caliber = object.caliber ?? "";
    message.deviceUuid = object.deviceUuid ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
