name: Python

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      - name: Run ruff
        run: uv run ruff check

  test:
    name: Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./py

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest
